future:      true
lsi:         true
pygments:    true
markdown:    maruku
permalink:   date
destination: _site/
plugins:     _plugins



name: Ulrichs blog
description: Everything and nothing
url: http://dangel.im
paginate: 2
baseurl: /
permalink: /blog/:categories/:year/:month/:day/:title.html
